# Generated by Django 4.1.5 on 2023-01-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_testmodel_slg'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='slg2',
            field=models.SlugField(default='221533475!@#%@#$^#$^@3abc-?'),
        ),
    ]
