# Generated by Django 4.1.5 on 2023-01-25 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0006_testmodel_slg2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='slg',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='slg2',
        ),
    ]
